# Exercise: visualisation and analysis of the dataset

In [1]:
# import libraries
import numpy
import matplotlib.pyplot as plt

# load dataset
data = numpy.loadtxt(fname= "data/inflammation-01.csv",
                    delimiter= ',')
print(data)

# add subplots

# add labels

# calculate the statistics: mean, max, min of patients over time (axis = 0)

# optional: save in a png

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
