In [1]:
import numpy

In [2]:
data = numpy.loadtxt(fname='data/inflammation-01.csv',delimiter=',')

In [3]:
type(data)

numpy.ndarray

In [4]:
print(data.shape)

(60, 40)


In [5]:
data.shape

(60, 40)

In [6]:
numpy.mean(data)

6.14875

In [7]:
numpy.mean(data[0:2,:2])

0.25

In [8]:
print(data[:2,:2])

[[0. 0.]
 [0. 1.]]


In [9]:
subset = data[:2,:2]
print(subset)

[[0. 0.]
 [0. 1.]]


In [10]:
numpy.mean(subset)

0.25

In [12]:
print(numpy.mean(subset,axis=0))

[0.  0.5]


In [13]:
print(numpy.mean(subset,axis=1))

[0.  0.5]


In [16]:
subset = data[0:3,-3:]
print(subset)

[[3. 0. 0.]
 [1. 0. 1.]
 [2. 1. 1.]]


In [19]:
# it sweeps the columns --- the result is a row
print(numpy.mean(subset,axis=0))

[2.         0.33333333 0.66666667]


In [20]:
# it sweeps the rows ... the result is a column 
print(numpy.mean(subset,axis=1))

[1.         0.66666667 1.33333333]


In [22]:
# mean of disease among patients over time
print(numpy.mean(data,axis=0))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


In [23]:
print(numpy.mean(data, axis=0).shape)

(40,)
