## Variables

In [1]:
3+5*4

23

In [9]:
weight_kg=60

In [3]:
weig6_=10

In [4]:
6weight

SyntaxError: invalid decimal literal (2998321253.py, line 1)

In [5]:
Weight_kg

NameError: name 'Weight_kg' is not defined

In [6]:
weight_kg=60.3

In [7]:
patient_id="001"

In [8]:
patient_id

'001'

In [10]:
weight_lb=2.2*weight_kg

In [11]:
weight_lb

132.0

In [12]:
patient_id="inflam"+patient_id

In [13]:
patient_id

'inflam001'

In [14]:
print(patient_id)

inflam001


In [15]:
print(weight_lb)

132.0


In [16]:
print(patient_id,"weight in kg:",weight_kg)

inflam001 weight in kg: 60


In [17]:
type(patient_id)

str

In [18]:
type(weight_kg)

int

In [19]:
type(weight_lb)

float

In [21]:
print(type(weight_kg))#print the type of weight_kg

<class 'int'>


## Lists 

In [22]:
odds=[1,3,5,7]

In [23]:
print("the first element:",odds[0])

the first element: 1


In [24]:
print("the second element:",odds[1])

the second element: 3


In [25]:
print("the last element:",odds[3])

the last element: 7


In [26]:
print("the last element:",odds[-1])

the last element: 7


In [27]:
veg=[["lettuce","tomato","peppers"],["cucumber"],["cilantro","zucchini"]]

In [29]:
veg[0][0]

'lettuce'

In [31]:
veg[1][0]

'cucumber'

In [34]:
veg[0:2]

[['lettuce', 'tomato', 'peppers'], ['cucumber']]

In [35]:
names=["Curie","Darwing","Turing"] 

In [36]:
print("names are",names)

names are ['Curie', 'Darwing', 'Turing']


In [37]:
names[1]="Darwin"

In [38]:
print("now names are",names)

now names are ['Curie', 'Darwin', 'Turing']


In [40]:
names="Darwin"

In [42]:
names[0]

'D'

In [43]:
odds

[1, 3, 5, 7]

In [44]:
odds.append(9)

In [45]:
odds

[1, 3, 5, 7, 9]

In [46]:
removed_element=odds.pop(0)

In [47]:
print("odds after removing first element",odds)

odds after removing first element [3, 5, 7, 9]


In [48]:
print("removed element",removed_element)

removed element 1


In [49]:
type(removed_element)

int

## Load data

In [4]:
import numpy

In [2]:
numpy.loadtxt(fname="data/inflammation-01.csv",delimiter=",")

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [7]:
data = numpy.loadtxt(fname= 'data/inflammation-01.csv', delimiter = ",")

In [8]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
