## Variables

In [1]:
3+5*4

23

In [2]:
import numpy
data = numpy.loadtxt(fname = 'data/inflammation-01.csv', delimiter = ',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
