## Variables

In [1]:
3+5*4

23

In [5]:
import numpy

In [6]:
data = numpy.loadtxt(fname = 'data/inflammation-01.csv', delimiter = ',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [7]:
data.shape

(60, 40)

# this is my part 

In [1]:
print("Raul rules")

Raul rules
