## FUNDAMENTALS

An introduction to episode: https://swcarpentry.github.io/python-novice-inflammation/01-intro.html

In [1]:
# python as calculator
2 + 3 * 6 + 4

24

In [2]:
# variable assignment
weight_kg = 60

In [3]:
# variable name have syntax requirements
0weight_kg = 60

SyntaxError: invalid syntax (<ipython-input-3-dcfa20cf517b>, line 2)

In [4]:
# variables have type
# example of built-in function
type(weight_kg)

int

In [5]:
# variables can be reassigned
weight_kg = 60.4

In [6]:
# the type is assigned based on the value
type(weight_kg)

float

In [7]:
# another built-in function
print(weight_kg)

60.4


In [8]:
# assignments can be used as formulas
weight_lb = 2.2 * weight_kg

In [9]:
print(weight_lb)

132.88


In [10]:
# variable assignment
# the value is string (of characters)
# a string is enclosed between quotes
patient_id = '001'

In [11]:
# string is a type python recognises 
type(patient_id)

str

In [12]:
print(patient_id)

001


In [13]:
# different operations can be expressed with the same operator
# + does not mean addition here
# this is called operator overloading
patient_id = 'inflam_' + patient_id

In [14]:
print(patient_id)

inflam_001


In [15]:
# a function can take more than one parameter (argument), comma-separated
print(patient_id, 'weight in kilogram:', weight_kg) 

inflam_001 weight in kilogram: 60.4


In [16]:
type(56)

int

In [17]:
# functions can be nested
print(type(56))

<class 'int'>


In [18]:
# operations can be part of functions parameter
print('weight in pound:', 2.2 * weight_kg)

weight in pound: 132.88


In [19]:
# applications:
mass = 47.5
age = 22 # if you delete `age = 122` from the cell, the variable age and its values persist in the memory

In [20]:
print(mass)

47.5


In [21]:
print(age)

22


In [22]:
print(mass, age)

47.5 22


In [23]:
# this built-in function really deletes the variable (wiped out at memory level)
del(age)

In [24]:
# expected failure: python throws an error message (see episode 11 in Carpentries
print(age)

NameError: name 'age' is not defined

In [ ]:
# give a pair of variables a pair of values
first, second = 'Grace', 'Hopper'

In [25]:
print(first)
print(second)

NameError: name 'first' is not defined

In [26]:
# repeat
third, fourth = first, second
print(third)
print(fourth)
print(first, third)

NameError: name 'first' is not defined

In [27]:
# application
planet = 'Earth'
apples = 5
distance = 10.5

In [28]:
# find types
# you only see the last ouput (jupyterlab default behaviour)
type(planet)
type(apples)
type(distance)

float

In [29]:
# repeated prints shows each output
print(planet)
print(apples)
print(distance)

Earth
5
10.5


~~type((planet, apples, distance))~~

In [30]:
# show the type of three variable with a function with three parameters
print(type(planet), type(apples), type(distance))

<class 'str'> <class 'int'> <class 'float'>


---
## LISTS

An introduction to episode https://swcarpentry.github.io/python-novice-inflammation/04-lists.html

In [31]:
# construct a list and define a variable
odds = [1, 3, 5, 7]

In [32]:
type(odds)

list

In [33]:
# work with entire list
print('odds are:', odds)

odds are: [1, 3, 5, 7]


In [34]:
# use single elements of the list
# indices start from 0 (convention)
print('first element is:', odds[0])

first element is: 1


In [35]:
print('ĺast element is:', odds[3]) 

ĺast element is: 7


In [36]:
# negative indices are permitted and have a special use
print('which item is', odds[-2], '?')

which item is 5 ?


In [37]:
# application: a list with an intended typo
names = [ 'Curie', 'Darwing', 'Turing' ]

In [38]:
# type of the list
type(names)

list

In [39]:
# type of the elements of the list
type(names[0])

str

In [40]:
# reassign the element of a list (it is possible = the list is a mutable type)
names[1] = 'Darwin'

In [41]:
print(names)

['Curie', 'Darwin', 'Turing']


In [42]:
# the types of list items may vary
mixed = [ 1, 'one']

In [43]:
# application: copy of lists
mild_salsa = ['peppers', 'onions', 'cilantro', 'tomatoes']

In [44]:
hot_salsa = mild_salsa

In [45]:
hot_salsa[0] = 'red hot chili peppers'

In [46]:
# expected result
print('ingredients in hot salsa:', hot_salsa)

ingredients in hot salsa: ['red hot chili peppers', 'onions', 'cilantro', 'tomatoes']


In [47]:
# unexpected result: also the other list has changed its item
print('ingredients in mild salsa:', mild_salsa)

ingredients in mild salsa: ['red hot chili peppers', 'onions', 'cilantro', 'tomatoes']


In [48]:
# fix the mistake and restart
mild_salsa[0] = 'peppers'

In [49]:
print(hot_salsa)

['peppers', 'onions', 'cilantro', 'tomatoes']


In [50]:
# different way of copying lists (deep copy)
hot_salsa = list(mild_salsa)

In [51]:
hot_salsa[0] = 'hot peppers'

In [52]:
print(hot_salsa)

['hot peppers', 'onions', 'cilantro', 'tomatoes']


In [53]:
# desired results: the other list has not been affected
print(mild_salsa)

['peppers', 'onions', 'cilantro', 'tomatoes']


In [54]:
# question: does that behaviour only occur with list?
# test: try with integers
a = 10

In [55]:
b = a

In [56]:
b = 5.0

In [57]:
print(a)

10


In [58]:
print(b)
# answer: no, both variables keep an own value

5.0


In [59]:
# nested lists (list of list)
nested_list = [['a', 'b', 'c'], ['i', 'j', 'k'], ['x', 'y', 'z']]

In [60]:
print(nested_list)

[['a', 'b', 'c'], ['i', 'j', 'k'], ['x', 'y', 'z']]


In [61]:
type(nested_list)

list

In [62]:
# address the element in a nested list
print(nested_list[1])

['i', 'j', 'k']


In [63]:
type(nested_list[1])

list

In [64]:
# address an element in a list in a nested list
# note the syntax is logical
print(nested_list[1][1])

j


In [65]:
# another built-in function
len(nested_list)

3

In [66]:
len(hot_salsa)

4

In [67]:
# similarities between lists and strings
binomial_name = 'Drosophila melanogaster'

In [68]:
type(binomial_name)

str

In [69]:
len(binomial_name)

23

In [70]:
print(binomial_name)

Drosophila melanogaster


In [71]:
# slices are intervals of lists and strings
# example with the full length
# in the slice range the last element is not included
# the length of the range is the difference between endpoints
print(binomial_name[0:23])

Drosophila melanogaster


In [72]:
# binomial name = group + species
group = binomial_name[0:10]

In [73]:
print(group)

Drosophila


In [74]:
len(group)

10

In [75]:
species = binomial_name[11:23]

In [76]:
print(species)

melanogaster


In [77]:
len(species)

12

In [78]:
# change a string by changing an element of it
# not permitted because string is an immutable type
# (assign the string in full again, if a change is wished)
species[2] = 'X'
print(species)
print(binomial_name)

TypeError: 'str' object does not support item assignment

In [79]:
# repeat
print(binomial_name)

Drosophila melanogaster


In [80]:
print(binomial_name[0:23])

Drosophila melanogaster


In [81]:
# third parameter in the slice: the step or stride
print(binomial_name[0:23:2])

Doohl eaoatr


In [82]:
# permitted omissions of slice parameters
print(binomial_name[0:23:])

Drosophila melanogaster


In [83]:
print(binomial_name[:23:])

Drosophila melanogaster


In [84]:
print(binomial_name[::])

Drosophila melanogaster


In [85]:
print(binomial_name[-11:])

elanogaster


In [86]:
# slice with negative numbers
print(binomial_name[-11:-4])

elanoga


In [87]:
# slices with lists (after the strings)
numbers = [0, 1, 2, 3, 4]

In [88]:
len(numbers)

5

In [89]:
print(numbers)

[0, 1, 2, 3, 4]


In [90]:
print(numbers[0:5])

[0, 1, 2, 3, 4]


In [91]:
print(numbers[0:4])

[0, 1, 2, 3]


---
## FOR LOOPS

An introduction to episode: https://swcarpentry.github.io/python-novice-inflammation/05-loop.html

In [92]:
# start off with a list
print(odds)

[1, 3, 5, 7]


In [93]:
# lengty way to print result
print(odds[0])
print(odds[1])
print(odds[-2])
print(odds[-1])

1
3
5
7


In [94]:
# smart way to print result
# try and comment in the line in the for block 
for loop_variable in odds:
    print(loop_variable)
    # print('sunshine')

1
3
5
7


In [95]:
# the name of the loop variable is unimportant
for banana in odds:
    print(banana)

1
3
5
7


In [96]:
# using the loop variable in the body is not mandatory
for number in odds:
    print('hello world')

hello world
hello world
hello world
hello world


In [97]:
# anothe application with a list
print(names)

['Curie', 'Darwin', 'Turing']


In [98]:
# difference between loop variable and list 1
for value in names:
    print(names)

['Curie', 'Darwin', 'Turing']
['Curie', 'Darwin', 'Turing']
['Curie', 'Darwin', 'Turing']


In [99]:
# difference between loop variable and list 2
for value in names:
    print(value)

Curie
Darwin
Turing


In [100]:
len(names)

3

In [101]:
# compute the length with a loop
# change variables defined before the loop
length = 0
for values in names:
    length = length + 1

# indent the text back to finish the block
print(length)

3


In [102]:
# shortcut for incrementing the same variable 
# += is a case of in-place operator
length = 0
for values in names:
    length += 1
print(length)

3


In [103]:
# create a sequence of integer number
for number in range(4):
    print(number)

0
1
2
3


In [104]:
# like lists, but not exactly lists
for number in range(0:4):
    print(number)

SyntaxError: invalid syntax (<ipython-input-104-0b8e886ef464>, line 2)

In [105]:
# range is a function: parameters are separated by commas
# same meaning as indices in a slice
for number in range(0, 4):
    print(number)

0
1
2
3


In [106]:
for number in range(4, 8):
    print(number)

4
5
6
7


In [107]:
# third parameter of range() has same meaning as slice 
for number in range(345, 467, 56):
    print(number)

345
401
457


In [108]:
# start off with a list
# obtain the values of the list
for number in odds:
    print(number)

1
3
5
7


In [109]:
# obtain both index and value of a list
for index, value in enumerate(odds):
    print('index:', index, 'contains value:' , value)

index: 0 contains value: 1
index: 1 contains value: 3
index: 2 contains value: 5
index: 3 contains value: 7


---
## IMPORT MODULES (aka LIBRARIES) AND ANALYSE DATA

See episode: https://swcarpentry.github.io/python-novice-inflammation/02-numpy.html

In [110]:
# numerical python
import numpy

In [111]:
# functions in libraries (extend the set of built-in functions)
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [112]:
# type of a value created with a library function (module method)
# ndarray = n-dimensional array
type(data)

numpy.ndarray

In [113]:
# like a list of list but not really (not comma-separated)
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [114]:
# dimension and size of data
print(data.shape)

(60, 40)


In [115]:
# type of the data elements (not of data)
print(data.dtype)

float64


In [116]:
# slices of data
# the full thing first
print(data[0:60, 0:40])

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [117]:
# slices of data and permitted omissions
print(data[0:6, :4])

[[0. 0. 1. 3.]
 [0. 1. 2. 1.]
 [0. 1. 1. 3.]
 [0. 0. 2. 0.]
 [0. 1. 1. 3.]
 [0. 0. 1. 2.]]


In [118]:
# select a slice of rows = select some rows = the columns are truncated
# select the whole columns = the rows are not truncated
print(data[0:6, ])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7. 10.  7.  9. 13.  8.  8. 15. 10.
  10.  7. 17.  4.  4.  7.  6. 15.  6.  4.  9. 11.  3.  5.  6.  3.  3.  4.
   2.  3.  2.  1.]
 [ 0.  1.  1.  3.  3.  1.  3.  5.  2.  4.  4.  7.  6.  5.  3. 10.  8. 10.
   6. 17.  9. 14.  9.  7. 13.  9. 12.  6.  7.  7.  9.  6.  3.  2.  2.  4.
   2.  0.  1.  1.]
 [ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.  7.  6.  6.  9.  9. 15.  4. 16.
  18. 12. 12.  5. 18.  9.  5.  3. 10.  3. 12.  7.  8.  4.  7.  3.  5.  4.
   4.  3.  2.  1.

In [119]:
# colon or no parameter has the same effect
print(data[0:3, :])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]]


In [120]:
# apply slicing to two dimensions of the (numpy) array
print(data[0:3, -3:])

[[3. 0. 0.]
 [1. 0. 1.]
 [2. 1. 1.]]


In [121]:
print(data[0:3:2, -3::2])

[[3. 0.]
 [2. 1.]]


In [122]:
print(data[0:3:2, -3::2].shape)

(2, 2)


In [123]:
# examples of operations available with numpy

In [124]:
# mean of all data (60x40=2400 data points)
numpy.mean(data)

6.14875

In [125]:
# standard deviation 
numpy.std(data)

4.613833197118566

In [126]:
# maximum value (amax = array maximum)
numpy.amax(data)

20.0

In [127]:
# minimum value
numpy.amin(data)

0.0

In [128]:
# show results in a triplet (shown as a 'tuple' of three elements)
numpy.amin(data), numpy.mean(data), numpy.amax(data)

(0.0, 6.14875, 20.0)

In [129]:
# assignement to multiple variables
minval, meanval, maxval = numpy.amin(data), numpy.mean(data), numpy.amax(data)

In [130]:
print(minval, meanval, maxval)

0.0 6.14875 20.0


In [131]:
# module functions (aka methods) and full variable
print(numpy.mean(data))

6.14875


In [132]:
# module functions (aka methods) and slices
print(numpy.mean(data[0, ]))

5.45


In [133]:
# not all functions need to have parameters (arguments) to work
import time
print(time.ctime())

Tue May 23 20:09:15 2023


---
## GETTING HELP

In [134]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [135]:
help(numpy.mean)

Help on function mean in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.

---

In [136]:
# final application that condenses most of the day
for row in range(data.shape[0]):
    print('the mean of row', row, 'is', numpy.mean(data[row,]))

the mean of row 0 is 5.45
the mean of row 1 is 5.425
the mean of row 2 is 6.1
the mean of row 3 is 5.9
the mean of row 4 is 5.55
the mean of row 5 is 6.225
the mean of row 6 is 5.975
the mean of row 7 is 6.65
the mean of row 8 is 6.625
the mean of row 9 is 6.525
the mean of row 10 is 6.775
the mean of row 11 is 5.8
the mean of row 12 is 6.225
the mean of row 13 is 5.75
the mean of row 14 is 5.225
the mean of row 15 is 6.3
the mean of row 16 is 6.55
the mean of row 17 is 5.7
the mean of row 18 is 5.85
the mean of row 19 is 6.55
the mean of row 20 is 5.775
the mean of row 21 is 5.825
the mean of row 22 is 6.175
the mean of row 23 is 6.1
the mean of row 24 is 5.8
the mean of row 25 is 6.425
the mean of row 26 is 6.05
the mean of row 27 is 6.025
the mean of row 28 is 6.175
the mean of row 29 is 6.55
the mean of row 30 is 6.175
the mean of row 31 is 6.35
the mean of row 32 is 6.725
the mean of row 33 is 6.125
the mean of row 34 is 7.075
the mean of row 35 is 5.725
the mean of row 36 is 5.92

### END OF DAY ONE
---