In [1]:
import numpy

In [2]:
data = numpy.loadtxt(fname='data/inflammation-01.csv',delimiter=',')

In [3]:
type(data)

numpy.ndarray

In [4]:
print(data.shape)

(60, 40)


In [5]:
data.shape

(60, 40)

In [6]:
numpy.mean(data)

6.14875

In [7]:
numpy.mean(data[0:2,:2])

0.25

In [8]:
print(data[:2,:2])

[[0. 0.]
 [0. 1.]]


In [9]:
subset = data[:2,:2]
print(subset)

[[0. 0.]
 [0. 1.]]


In [10]:
numpy.mean(subset)

0.25

In [12]:
print(numpy.mean(subset,axis=0))

[0.  0.5]


In [13]:
print(numpy.mean(subset,axis=1))

[0.  0.5]


In [16]:
subset = data[0:3,-3:]
print(subset)

[[3. 0. 0.]
 [1. 0. 1.]
 [2. 1. 1.]]
