# Python day 1

This is plain text

## 1. Python fundamentals

In [1]:
2 + 2

4

In [2]:
weight_kg = 60 #kilograms

In [3]:
weight_kg

60

In [4]:
1_patient_weight = 62

SyntaxError: invalid decimal literal (1419232609.py, line 1)

In [5]:
Weight_kg

NameError: name 'Weight_kg' is not defined

### Types of data

In [6]:
weight_kg = 60.3 #floating point

In [7]:
patient_id = "001" #string

In [8]:
weight_lb = weight_kg * 2.2

In [9]:
weight_lb

132.66

In [10]:
patient_id = "inflam_" + patient_id

In [11]:
patient_id

'inflam_001'

In [12]:
type(patient_id)

str

In [13]:
type(weight_kg)

float

In [14]:
print(weight_kg)

60.3


In [15]:
print(patient_id, weight_kg)

inflam_001 60.3


In [16]:
#Automatic type determination
x = 4 / 3
print(x)
print(type(x))

1.3333333333333333
<class 'float'>


## 1.2 Python lists

In [17]:
odds = [1, 3, 5, 7]
print('odds are: ', odds)

odds are:  [1, 3, 5, 7]


In [18]:
odds[0]

1

In [19]:
print(odds[3])

7


In [20]:
odds[14]

IndexError: list index out of range

In [21]:
names = ['Curie', 'Darwing', 'Turing']
print(names)

['Curie', 'Darwing', 'Turing']


In [22]:
names[1] = 'Darwin'
print(names)

['Curie', 'Darwin', 'Turing']


In [23]:
salsa = ['peppers', 'onions', 'cilantro', 'tomatoes']
print(salsa)

['peppers', 'onions', 'cilantro', 'tomatoes']


In [24]:
my_salsa = salsa
print(my_salsa)

['peppers', 'onions', 'cilantro', 'tomatoes']


In [25]:
my_salsa[0] = 'hot_peppers'

In [26]:
print(my_salsa)

['hot_peppers', 'onions', 'cilantro', 'tomatoes']


In [27]:
print(salsa)

['hot_peppers', 'onions', 'cilantro', 'tomatoes']


In [28]:
salsa = ['peppers', 'onions', 'cilantro', 'tomatoes']
print(salsa)

['peppers', 'onions', 'cilantro', 'tomatoes']


In [29]:
my_salsa = list(salsa)

In [30]:
print(my_salsa)

['peppers', 'onions', 'cilantro', 'tomatoes']


In [31]:
my_salsa[0] = 'hot_peppers'
print(my_salsa)
print(salsa)

['hot_peppers', 'onions', 'cilantro', 'tomatoes']
['peppers', 'onions', 'cilantro', 'tomatoes']


In [32]:
matrix = [ [1, 2, 3],  [4, 5, 6],  [7, 8, 9]  ]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [34]:
odds.index(5)

2

In [35]:
matrix[1][1]

5

# 2. Analysing data

In [36]:
import numpy

In [37]:
data = numpy.loadtxt(fname="data/inflammation-01.csv", delimiter =',')

In [38]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [39]:
type(data)

numpy.ndarray

In [40]:
print(data.dtype)

float64


In [41]:
print(data.shape)

(60, 40)


In [42]:
data[0, 0]

0.0

## Slicing data

In [43]:
data[0:4, 0:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [44]:
data[:4, :10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [45]:
data[-1,-1]

0.0

In [46]:
data[:3, -4:]

array([[2., 3., 0., 0.],
       [1., 1., 0., 1.],
       [2., 2., 1., 1.]])

## Analysing patient data

In [47]:
print(numpy.mean(data))

6.14875


In [48]:
maxval = numpy.max(data)

In [49]:
maxval

20.0

In [50]:
maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)

print(maxval, minval, stdval)



20.0 0.0 4.613833197118566


In [51]:
#Option 1
patient_0 = data[0,:]
print(numpy.max(patient_0))

18.0


In [52]:
#Option 2
print(numpy.max(data, axis=1))

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]
