## Variables

In [1]:
3+5*4

23

In [9]:
weight_kg=60

In [3]:
weig6_=10

In [4]:
6weight

SyntaxError: invalid decimal literal (2998321253.py, line 1)

In [5]:
Weight_kg

NameError: name 'Weight_kg' is not defined

In [6]:
weight_kg=60.3

In [7]:
patient_id="001"

In [8]:
patient_id

'001'

In [10]:
weight_lb=2.2*weight_kg

In [11]:
weight_lb

132.0

In [12]:
patient_id="inflam"+patient_id

In [13]:
patient_id

'inflam001'

In [14]:
print(patient_id)

inflam001


In [15]:
print(weight_lb)

132.0


In [16]:
print(patient_id,"weight in kg:",weight_kg)

inflam001 weight in kg: 60


In [17]:
type(patient_id)

str

In [18]:
type(weight_kg)

int

In [19]:
type(weight_lb)

float

In [21]:
print(type(weight_kg))#print the type of weight_kg

<class 'int'>


## Lists 

In [22]:
odds=[1,3,5,7]

In [23]:
print("the first element:",odds[0])

the first element: 1


In [24]:
print("the second element:",odds[1])

the second element: 3


In [25]:
print("the last element:",odds[3])

the last element: 7


In [26]:
print("the last element:",odds[-1])

the last element: 7


In [27]:
veg=[["lettuce","tomato","peppers"],["cucumber"],["cilantro","zucchini"]]

In [29]:
veg[0][0]

'lettuce'

In [31]:
veg[1][0]

'cucumber'

In [34]:
veg[0:2]

[['lettuce', 'tomato', 'peppers'], ['cucumber']]

In [35]:
names=["Curie","Darwing","Turing"] 

In [36]:
print("names are",names)

names are ['Curie', 'Darwing', 'Turing']


In [37]:
names[1]="Darwin"

In [38]:
print("now names are",names)

now names are ['Curie', 'Darwin', 'Turing']


In [40]:
names="Darwin"

In [42]:
names[0]

'D'

In [43]:
odds

[1, 3, 5, 7]

In [44]:
odds.append(9)

In [45]:
odds

[1, 3, 5, 7, 9]

In [46]:
removed_element=odds.pop(0)

In [47]:
print("odds after removing first element",odds)

odds after removing first element [3, 5, 7, 9]


In [48]:
print("removed element",removed_element)

removed element 1


In [49]:
type(removed_element)

int

## Load data

In [4]:
import numpy

In [2]:
numpy.loadtxt(fname="data/inflammation-01.csv",delimiter=",")

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [7]:
data = numpy.loadtxt(fname= 'data/inflammation-01.csv', delimiter = ",")

In [8]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [9]:
%whos

Variable   Type       Data/Info
-------------------------------
data       ndarray    60x40: 2400 elems, type `float64`, 19200 bytes
numpy      module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [10]:
type(data)

numpy.ndarray

In [11]:
data.dtype

dtype('float64')

In [12]:
data.shape

(60, 40)

In [13]:
print("the first value in data is..", data[0,0])

the first value in data is.. 0.0


In [16]:
print("the middle value is data is..", data[29,19])

the middle value is data is.. 16.0


In [17]:
# slicing data

data[0:4,0:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

**Analysing data**

In [18]:
numpy.mean(data)

6.14875

In [20]:
# median is
numpy.median(data)

5.0

In [21]:
# max
numpy.amax(data)

20.0

In [23]:
# variables
maxval, minval, stdval = numpy.amax(data), numpy.amin(data), numpy.std(data)

# print the variables
print("maximum inflammation:", maxval)
print("min inflammation:", minval)
print("standard deviation:", round(stdval, 2))

maximum inflammation: 20.0
min inflammation: 0.0
standard deviation: 4.61


In [25]:
# max inflammation patient_0
patient_0 = data[0, :]
print("max inflammation for patient 0:", numpy.amax(patient_0))

max inflammation for patient 0: 18.0


In [28]:
# median of the patient number 2 for all the days
print("median inflammation for patient 2:", numpy.median(data[1, :]))

median inflammation for patient 2: 4.5


## what if we need the max inflammation for each patient over all days?

In [29]:
print(numpy.mean(data, axis=0))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


In [30]:
numpy.mean(data, axis = 0).shape

(40,)

In [31]:
numpy.mean(data, axis = 1)

array([5.45 , 5.425, 6.1  , 5.9  , 5.55 , 6.225, 5.975, 6.65 , 6.625,
       6.525, 6.775, 5.8  , 6.225, 5.75 , 5.225, 6.3  , 6.55 , 5.7  ,
       5.85 , 6.55 , 5.775, 5.825, 6.175, 6.1  , 5.8  , 6.425, 6.05 ,
       6.025, 6.175, 6.55 , 6.175, 6.35 , 6.725, 6.125, 7.075, 5.725,
       5.925, 6.15 , 6.075, 5.75 , 5.975, 5.725, 6.3  , 5.9  , 6.75 ,
       5.925, 7.225, 6.15 , 5.95 , 6.275, 5.7  , 6.1  , 6.825, 5.975,
       6.725, 5.7  , 6.25 , 6.4  , 7.05 , 5.9  ])