In [3]:
2 + 3 * 6 + 4

24

In [4]:
weight_kg = 60

In [5]:
0weight_kg = 60

SyntaxError: invalid syntax (<ipython-input-5-12d5035ace32>, line 1)

In [6]:
type(weight_kg)

int

In [7]:
weight_kg = 60.4

In [8]:
type(weight_kg)

float

In [9]:
print(weight_kg)

60.4


In [10]:
weight_lb = 2.2 * weight_kg

In [11]:
print(weight_lb)

132.88


In [12]:
patient_id = '001'

In [13]:
type(patient_id)

str

In [14]:
print(patient_id)

001


In [15]:
patient_id = 'inflam_' + patient_id

In [16]:
print(patient_id)

inflam_001


In [17]:
print(patient_id, 'weight in kilogram:', weight_kg) 

inflam_001 weight in kilogram: 60.4


In [18]:
type(56)

int

In [19]:
print(type(56))

<class 'int'>


In [20]:
print('weight in pound:', 2.2 * weight_kg)

weight in pound: 132.88


In [21]:
mass = 47.5

In [22]:
print(mass)

47.5


In [24]:
print(age)

122


In [26]:
print(mass, age)

47.5 122


In [27]:
del(age)

In [28]:
print(age)

NameError: name 'age' is not defined

In [29]:
first, second = 'Grace', 'Hopper'

In [30]:
print(first)
print(second)

Grace
Hopper


In [31]:
third, fourth = first, second
print(third)
print(fourth)
print(first, third)

Grace
Hopper
Grace Grace


In [32]:
planet = 'Earth'
apples = 5
distance = 10.5

In [33]:
type(planet)
type(apples)
type(distance)

float

In [34]:
print(planet)
print(apples)
print(distance)

Earth
5
10.5


In [36]:
type((planet, apples, distance))

tuple

In [37]:
print(type(planet), type(apples), type(distance))

<class 'str'> <class 'int'> <class 'float'>


In [38]:
# LISTS

In [39]:
odds = [1, 3, 5, 7]

In [40]:
type(odds)

list

In [41]:
print('odds are:', odds)

odds are: [1, 3, 5, 7]


In [42]:
print('first element is:', odds[0])

first element is: 1


In [43]:
print('ĺast element is:', odds[3]) 

ĺast element is: 7


In [45]:
print('which element is:', odds[-2], '?')

which element is: 5 ?


In [46]:
names = [ 'Curie', 'Darwing', 'Turing' ]

In [47]:
type(names)

list

In [48]:
type(names[0])

str

In [49]:
names[1] = 'Darwin'

In [50]:
print(names)

['Curie', 'Darwin', 'Turing']


In [51]:
mixed = [ 1, 'one']

In [52]:
mild_salsa = ['peppers', 'onions', 'cilantro', 'tomatoes']

In [53]:
hot_salsa = mild_salsa

In [54]:
hot_salsa[0] = 'red hot chili peppers'

In [55]:
print('ingredients in hot salsa:', hot_salsa)

ingredients in hot salsa: ['red hot chili peppers', 'onions', 'cilantro', 'tomatoes']


In [56]:
print('ingredients in mild salsa:', mild_salsa)

ingredients in mild salsa: ['red hot chili peppers', 'onions', 'cilantro', 'tomatoes']


In [57]:
mild_salsa[0] = 'peppers'

In [58]:
print(hot_salsa)

['peppers', 'onions', 'cilantro', 'tomatoes']


In [59]:
hot_salsa = list(mild_salsa)

In [60]:
hot_salsa[0] = 'hot peppers'

In [61]:
print(hot_salsa)

['hot peppers', 'onions', 'cilantro', 'tomatoes']


In [62]:
print(mild_salsa)

['peppers', 'onions', 'cilantro', 'tomatoes']


In [63]:
 a = 10

In [64]:
b = a

In [65]:
b = 5.0

In [66]:
print(a)

10


In [67]:
print(b)

5.0


In [69]:
nested_list = [['a', 'b', 'c'], ['i', 'j', 'k'], ['x', 'y', 'z']]

In [70]:
print(nested_list)

[['a', 'b', 'c'], ['i', 'j', 'k'], ['x', 'y', 'z']]


In [71]:
type(nested_list)

list

In [72]:
print(nested_list[1])

['i', 'j', 'k']


In [73]:
type(nested_list[1])

list

In [74]:
print(nested_list[1][1])

j


In [75]:
# WE RESUME AT 14:10

In [76]:
len(nested_list)

3

In [77]:
len(hot_salsa)

4

In [78]:
binomial_name = 'Drosophila melanogaster'

In [79]:
type(binomial_name)

str

In [80]:
len(binomial_name)

23

In [81]:
print(binomial_name)

Drosophila melanogaster


In [82]:
print(binomial_name[0:23])

Drosophila melanogaster


In [83]:
group = binomial_name[0:10]

In [84]:
print(group)

Drosophila


In [85]:
len(group)

10

In [86]:
numbers = [0, 1, 2, 3, 4]

In [87]:
len(numbers)

5

In [88]:
print(numbers)

[0, 1, 2, 3, 4]


In [89]:
print(numbers[0:5])

[0, 1, 2, 3, 4]


In [90]:
print(numbers[0:4])

[0, 1, 2, 3]


In [91]:
species = binomial_name[11:23]

In [92]:
print(species)

melanogaster


In [93]:
len(species)

12

In [96]:
# I may not change a string by changing an element of it
# string is an immutable types
species[2] = 'X'
print(species)
print(binomial_name)

TypeError: 'str' object does not support item assignment

In [97]:
print(binomial_name)

Drosophila melanogaster


In [98]:
print(binomial_name[0:23])

Drosophila melanogaster


In [100]:
print(binomial_name[0:23:2])

Doohl eaoatr


In [101]:
print(binomial_name[0:23:])

Drosophila melanogaster


In [102]:
print(binomial_name[:23:])

Drosophila melanogaster


In [103]:
print(binomial_name[::])

Drosophila melanogaster


In [105]:
print(binomial_name[-11:])

elanogaster


In [106]:
print(binomial_name[-11:-4])

elanoga


In [107]:
# FOR LOOPS (ahead of the scheduled time)

In [108]:
print(odds)

[1, 3, 5, 7]


In [109]:
print(odds[0])
print(odds[1])
print(odds[-2])
print(odds[-1])

1
3
5
7


In [111]:
for loop_variable in odds:
    print(loop_variable)
    # print('sunshine')

1
3
5
7


In [112]:
for banana in odds:
    print(banana)

1
3
5
7


In [113]:
for number in odds:
    print('hello world')

hello world
hello world
hello world
hello world


In [114]:
print(names)

['Curie', 'Darwin', 'Turing']


In [116]:
for value in names:
    print(names)

['Curie', 'Darwin', 'Turing']
['Curie', 'Darwin', 'Turing']
['Curie', 'Darwin', 'Turing']


In [117]:
for value in names:
    print(value)

Curie
Darwin
Turing


In [118]:
len(names)

3

In [119]:
length = 0
for values in names:
    length = length + 1
# I indent it back to show this is not part of the block
print(length)

3


In [120]:
length = 0
for values in names:
    length += 1
print(length)

3


In [121]:
for number in range(4):
    print(number)

0
1
2
3


In [122]:
for number in range(0:4):
    print(number)

SyntaxError: invalid syntax (<ipython-input-122-2c7b664ccf2e>, line 1)

In [123]:
for number in range(0,4):
    print(number)

0
1
2
3


In [124]:
for number in range(4,8):
    print(number)


4
5
6
7


In [125]:
for number in range(345,467,56):
    print(number)


345
401
457


In [126]:
for number in odds:
    print(number)

1
3
5
7


In [128]:
for index, value in enumerate(odds):
    print('index:', index, 'contains value:' , value)

index: 0 contains value: 1
index: 1 contains value: 3
index: 2 contains value: 5
index: 3 contains value: 7


In [129]:
# WE RESUME AT 15:45

In [130]:
import numpy

In [132]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [133]:
type(data)

numpy.ndarray

In [134]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [135]:
print(data.shape)

(60, 40)


In [136]:
print(data.dtype)

float64


In [137]:
print(data[0:60,0:40])

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [138]:
print(data[0:6, :4])

[[0. 0. 1. 3.]
 [0. 1. 2. 1.]
 [0. 1. 1. 3.]
 [0. 0. 2. 0.]
 [0. 1. 1. 3.]
 [0. 0. 1. 2.]]


In [139]:
print(data[0:6,])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7. 10.  7.  9. 13.  8.  8. 15. 10.
  10.  7. 17.  4.  4.  7.  6. 15.  6.  4.  9. 11.  3.  5.  6.  3.  3.  4.
   2.  3.  2.  1.]
 [ 0.  1.  1.  3.  3.  1.  3.  5.  2.  4.  4.  7.  6.  5.  3. 10.  8. 10.
   6. 17.  9. 14.  9.  7. 13.  9. 12.  6.  7.  7.  9.  6.  3.  2.  2.  4.
   2.  0.  1.  1.]
 [ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.  7.  6.  6.  9.  9. 15.  4. 16.
  18. 12. 12.  5. 18.  9.  5.  3. 10.  3. 12.  7.  8.  4.  7.  3.  5.  4.
   4.  3.  2.  1.

In [140]:
print(data[0:3,:])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]]


In [141]:
print(data[0:3,-3:])

[[3. 0. 0.]
 [1. 0. 1.]
 [2. 1. 1.]]


In [142]:
print(data[0:3:2,-3::2])

[[3. 0.]
 [2. 1.]]


In [143]:
print(data[0:3:2, -3::2].shape)

(2, 2)


In [144]:
# operation

In [145]:
numpy.mean(data)

6.14875

In [146]:
numpy.std(data)

4.613833197118566

In [147]:
numpy.amax(data)

20.0

In [148]:
numpy.amin(data)

0.0

In [149]:
numpy.amin(data), numpy.mean(data), numpy.amax(data)

(0.0, 6.14875, 20.0)

In [150]:
minval, meanval, maxval = numpy.amin(data), numpy.mean(data), numpy.amax(data)

In [151]:
print(minval, meanval, maxval)

0.0 6.14875 20.0


In [152]:
import time
print(time.ctime())

Mon May 22 16:44:56 2023


In [153]:
# getting help

In [154]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [155]:
help(numpy.mean)

Help on function mean in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.

In [157]:
print(numpy.mean(data))

6.14875


In [ ]:
print(numpy.mean(d)